name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER}}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e  # 오류 발생 시 스크립트 중단
            
            echo "Checking initial system status..."
            free -h
            df -h
            sudo swapon --show

            echo "Cleaning up system resources..."
            # 로그 파일 정리 (중요 시스템 로그 제외)
            sudo find /var/log -type f \( -name "*.log" -o -name "*.gz" \) \
              ! -name "auth.log" \
              ! -name "syslog" \
              ! -name "kern.log" \
              -delete
            sudo find /var/log -type d -empty -delete
            sudo apt-get clean
            sudo apt-get autoremove -y
            sudo rm -rf /tmp/*
            sudo apt-get autoremove --purge -y

            echo "Setting up swap memory..."
            if [ ! -f /swapfile ]; then
              sudo fallocate -l 2G /swapfile
              sudo chmod 600 /swapfile
              sudo mkswap /swapfile
              sudo swapon /swapfile
              echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
            else
              echo "Swap file already exists."
            fi

            echo "Checking Docker daemon status..."
            if ! systemctl is-active --quiet docker; then
              echo "Docker daemon is not running. Starting Docker..."
              sudo systemctl start docker
            fi
            sudo systemctl status docker

            echo "Cleaning up Docker resources..."
            sudo docker system prune -af --volumes || echo "Docker cleanup failed, but continuing..."

            echo "System status after cleanup:"
            free -h
            df -h
            sudo docker info

            # 환경 변수 설정
            REPO_DIR=~/jsp-cafe
            BRANCH=main
            DOCKER_IMAGE=jsp-cafe:latest
            CONTAINER_PORT=8080

            echo "Stopping and removing existing containers..."
            CONTAINER_IDS=$(sudo docker ps -q --filter publish=$CONTAINER_PORT)
            if [ ! -z "$CONTAINER_IDS" ]; then
              sudo docker stop $CONTAINER_IDS
              sudo docker rm $CONTAINER_IDS
            else
              echo "No containers running on port $CONTAINER_PORT"
            fi

            echo "Updating or cloning repository..."
            if [ -d $REPO_DIR ]; then
              cd $REPO_DIR
              git fetch --all
              git reset --hard origin/$BRANCH
            else
              git clone https://github.com/kkyu0718/jsp-cafe.git $REPO_DIR
              cd $REPO_DIR
            fi
            git checkout $BRANCH
            git pull origin $BRANCH

            echo "Building Docker image..."
            sudo docker build --cache-from $DOCKER_IMAGE -t $DOCKER_IMAGE .

            echo "Running new container..."
            NEW_CONTAINER_ID=$(sudo docker run -d -p $CONTAINER_PORT:$CONTAINER_PORT --add-host=host.docker.internal:host-gateway $DOCKER_IMAGE)

            if [ -z "$NEW_CONTAINER_ID" ]; then
              echo "Failed to start new container"
              exit 1
            fi

            echo "New container ID: $NEW_CONTAINER_ID"
            echo "Deployment completed successfully"

            echo "Final system status:"
            free -h
            df -h
            sudo docker ps