name: Deploy to EC2

on:
  push:
    branches: [ step-8 ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER}}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Remove existing directory if it exists
            rm -rf ~/jsp-cafe
            # Clone the repository
            git clone https://github.com/kkyu0718/jsp-cafe.git ~/jsp-cafe
            # Navigate to the cloned directory
            cd ~/jsp-cafe
            # Checkout the specific branch (step-7 in this case)
            git checkout step-8
            # build docker
            docker build -t jsp-cafe .
            # Run the container
            docker run -d -p 8080:8080 jsp-cafe
#
#            # Stop Tomcat
#            sudo systemctl stop tomcat10
#            # Copy the WAR file
#            sudo cp ~/jsp-cafe/*.war /var/lib/tomcat10/webapps/ROOT.war
#            # Set correct ownership and permissions
#            sudo chown tomcat:tomcat /var/lib/tomcat10/webapps/ROOT.war
#            sudo chmod 644 /var/lib/tomcat10/webapps/ROOT.war
#            # Start Tomcat
#            sudo systemctl start tomcat10